stages:
  - build
  - test
  - package
  - deploy

# cache maven repo & nodejs modules
cache:
  paths:
    - apt-cache/
    - .m2/repository
    - node_modules/
    - target/

variables:
  JAVA_HOME: /usr/local/openjdk-11
  M2_HOME: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: integration-test
  GROUP_GITLAB: mohamed.karami
  APP_NAME: mobidata-mashup
  REPO: mobidatalab

build-job:
  stage: build
  image: maven:3.8.5-openjdk-11-slim
  tags:
    - mobidata-processor1
  script:
    - echo "Compiling the code..."
    - mvn install -B -DskipTests
    - echo "Compile complete!"
# cannot be used with external runners
#  artifacts:
#    paths:
#      - target/

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: maven:3.8.5-openjdk-11-slim
  tags:
    - mobidata-processor1
  script:
    - echo "Running unit tests..."
    - export APT_CACHE_DIR=apt-cache && mkdir -pv $APT_CACHE_DIR
    - DEBIAN_FRONTEND=noninteractive apt-get -qq update && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y unzip nodejs npm > /dev/null
    - apt update
    - apt -o dir::cache::archives="apt-cache" install -y unzip nodejs npm
    - nodejs --version
    - npm install -g osmtogeojson
    - mvn verify
    - echo "Unit tests execution complete."

package-job:   # This job runs in the test stage.
  stage: package    # It only starts when the job in the build stage completes successfully.
  image: maven:3.8.5-openjdk-11-slim
  tags:
    - mobidata-processor1
  script:
    - echo "Packaging application..."
    - mvn clean package -B -Dspring.profiles.active=prod -DskipTests
    - echo "Application packaged !"
  only:
    - main

deploy-job:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  tags:
    - mobidata-processor1
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - echo "Deploying application..."
    - docker build -t wanam/$REPO:latest .
    - docker push wanam/$REPO:latest
    - echo "Application successfully deployed."
  only:
    - main
  after_script:
    - docker logout