server:
  port: 8100
  max-http-header-size: 10MB

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
endpoints:
  navitia-uri: https://api.navitia.io/v1
  overpass-uri: https://www.overpass-api.de/api
  wikidata-uri: https://en.wikipedia.org

tokens:
  navitia-user-token: 55af740c-e0e9-4f2b-9387-3bb81a8c7bd4
  navitia-doc-token: 3b036afe-0110-4202-b9ed-99718476c2e0

#  navitia-uri: https://musicbrainz.org
#  overpass-uri: https://coverartarchive.org
#  wikidata-uri: https://en.wikipedia.org
proxy:
  proxy-host: and-fgt-ha.akka.eu
  proxy-port: 9090

---

spring:
  profiles: integration-test
endpoints:
  navitia-uri: http://localhost:8101
  wikidata-uri: http://localhost:8102
  overpass-uri: http://localhost:8103
proxy:
  proxy-host: and-fgt-ha.akka.eu
  proxy-port: 9090
