server:
  port: 443
  max-http-header-size: 10MB
  connection-timeout: 60
  ssl:
    enabled: true
    keyStoreType: PKCS12
    key-store: classpath:key-cert-mobidata.p12
    key-store-password: '@Kk4!Mob1d4ta'
  http:
    port: 80

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev

endpoints:
  navitia-uri: https://api.navitia.io/v1
  overpass-uri: https://www.overpass-api.de/api
  wikidata-uri: https://en.wikipedia.org
  here-uri: https://transit.router.hereapi.com/v8

tokens:
  navitia-user-token: 55af740c-e0e9-4f2b-9387-3bb81a8c7bd4
  navitia-doc-token: 3b036afe-0110-4202-b9ed-99718476c2e0

proxy:
  proxy-host: and-fgt-ha.akka.eu
  proxy-port: 9090

---

spring:
  config:
    activate:
      on-profile: integration-test

endpoints:
  navitia-uri: https://api.navitia.io/v1
  overpass-uri: https://www.overpass-api.de/api
  wikidata-uri: https://en.wikipedia.org
  here-uri: https://transit.router.hereapi.com/v8

tokens:
  navitia-user-token: 55af740c-e0e9-4f2b-9387-3bb81a8c7bd4
  navitia-doc-token: 3b036afe-0110-4202-b9ed-99718476c2e0

#proxy:
#  proxy-host: and-fgt-ha.akka.eu
#  proxy-port: 9090

---

spring:
  config:
    activate:
      on-profile: prod

endpoints:
  navitia-uri: https://api.navitia.io/v1
  overpass-uri: https://www.overpass-api.de/api
  wikidata-uri: https://en.wikipedia.org
  here-uri: https://transit.router.hereapi.com/v8

tokens:
  navitia-user-token: 55af740c-e0e9-4f2b-9387-3bb81a8c7bd4
  navitia-doc-token: 3b036afe-0110-4202-b9ed-99718476c2e0

#proxy:
#  proxy-host: and-fgt-ha.akka.eu
#  proxy-port: 9090
