server:
  port: 443
  ssl:
    enabled: true
    keyStoreType: PKCS12
    key-store: classpath:key-cert-mobidata.p12
    key-store-password: '@Kk4!Mob1d4ta'
  http:
    port: 80
  requests-rate-limit: 60 # requests per minute

spring:
  profiles:
    active: dev
  security:
    user:
      name: user
      password: password
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

---

spring:
  config:
    activate:
      on-profile: dev

endpoints:
  navitia-uri: https://api.navitia.io/v1
  overpass-uri: https://overpass.kumi.systems/api
  wikidata-uri: https://en.wikipedia.org
  here-uri: https://transit.router.hereapi.com/v8

#proxy:
#  proxy-host: and-fgt-ha.akka.eu
#  proxy-port: 9090

---

spring:
  config:
    activate:
      on-profile: integration-test

# random port required for travis-ci (we are not allowed to use 80 & 443)
server:
  port: 61443
  ssl:
    enabled: false
  http:
    port: 61080

endpoints:
  navitia-uri: https://api.navitia.io/v1
  overpass-uri: https://overpass.kumi.systems/api
  wikidata-uri: https://en.wikipedia.org
  here-uri: https://transit.router.hereapi.com/v8

#proxy:
#  proxy-host: and-fgt-ha.akka.eu
#  proxy-port: 9090

---

spring:
  config:
    activate:
      on-profile: prod

server:
  ssl:
    keyStoreType: PKCS12
    key-store: classpath:key-cert-mobidata.p12
    key-store-password: '@Kk4!Mob1d4ta'

endpoints:
  navitia-uri: https://api.navitia.io/v1
  overpass-uri: https://overpass.kumi.systems/api
  wikidata-uri: https://en.wikipedia.org
  here-uri: https://transit.router.hereapi.com/v8

#proxy:
#  proxy-host: and-fgt-ha.akka.eu
#  proxy-port: 9090
