name: Build and upload MDL docker image

env:
  SPRING_PROFILES_ACTIVE: integration-test
  REPO: mdl-geo-enrichment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: processor1-akka

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # build source code
      - name: Build
        run: mvn install -B -DskipTests

      # run unit and integration tests
      - name: Install OSM to GeoJson module
        run: npm install -g osmtogeojson # install osmtogeojson module
      - name: Install GTFS to GeoJson module
        run: npm install -g gtfs-to-geojson # install gtfs-to-geojson module
      - name: Run Integration tests
        run: mvn verify

      - name: Packaging...
        run: mvn clean package -B -Dspring.profiles.active=prod -DskipTests

      # build and deploy docker image
      - name: Connect to docker registry
        uses: docker/login-action@v2
        with:
          #registry: ghcr.io # GitHub's registry
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
          logout: true
      - name: Build docker image
        run: docker build -t wanam/${{ env.REPO }}:latest .
      - name: Push the image to docker registy
        run: docker push wanam/${{ env.REPO }}:latest
      - name: Stop the container of the old image if running
        run: docker stop $(docker ps -q --filter expose=80) || true
      - name: Run new docker image
        run: docker run -d -p 60080:80 -p 60443:443 wanam/${{ env.REPO }} --pull=always
